In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [3]:
data_test= pd.read_csv('data_for_testing.csv', delimiter=";")
data_from_users= pd.read_csv('data_from_users.csv', delimiter=";")
users_featured= pd.read_csv('users_featured.csv', delimiter=";")

In [42]:
from sklearn.model_selection import train_test_split

X = data_test.drop(columns=['plan']).values
X_columns = data_test.drop(columns=['plan']).columns
y = data_test['plan'].values

data_test.plan.value_counts()

0    14394
1     1150
Name: plan, dtype: int64

In [43]:
# transform the dataset
oversample = SMOTE()
X, y = oversample.fit_resample(X, y)
print(X.shape)
print(y.shape)

(28788, 51)
(28788,)


In [54]:
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y, test_size=0.2, stratify=y)
X_ts.shape

(5758, 51)

In [46]:
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y, test_size=0.2, stratify=y)
y_ts.shape

(5758,)

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
sampler = SMOTE()
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
rf = RandomForestClassifier()

Feature Selection

In [50]:
X.shape

(28788, 51)

In [69]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape

(28788, 38)

In [56]:
X_tr, X_ts, y_tr, y_ts = train_test_split(X_new, y, test_size=0.2, stratify=y)
X_ts.shape

(5758, 39)

Training Model

In [59]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report ,f1_score, roc_auc_score, roc_curve, recall_score , precision_score,accuracy_score , precision_recall_fscore_support

clf = LogisticRegression().fit(X_tr,y_tr)
clf_pred = clf.predict(X_ts)
print('accuracy: {:.2f}%'.format(accuracy_score(y_ts, clf_pred)*100))

# Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print('Accuracy Score : ' + str(accuracy_score(y_ts,clf_pred)))
print('Precision Score : ' + str(precision_score(y_ts,clf_pred)))
print('Recall Score : ' + str(recall_score(y_ts,clf_pred)))
print('F1 Score : ' + str(f1_score(y_ts,clf_pred)))

#Logistic Regression Classifier Confusion matrix
from sklearn.metrics import confusion_matrix
print('Confusion Matrix : \n' + str(confusion_matrix(y_ts,clf_pred)))

accuracy: 90.74%
Accuracy Score : 0.9074331365057312
Precision Score : 0.93125
Recall Score : 0.8798193817297673
F1 Score : 0.9048044293623861
Confusion Matrix : 
[[2692  187]
 [ 346 2533]]


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [81]:
#Grid Search
from sklearn.model_selection import GridSearchCV
clf = LogisticRegression()
grid_values1 = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values1,scoring = 'recall')
grid_clf_acc.fit(X_tr, y_tr)

#Predict values based on new parameters
clf_pred_acc = grid_clf_acc.predict(X_ts)
print(grid_clf_acc.best_params_, '\n')
# New Model Evaluation metrics 
print('Accuracy Score : ' + str(accuracy_score(y_ts,clf_pred_acc)))
print('Precision Score : ' + str(precision_score(y_ts,clf_pred_acc)))
print('Recall Score : ' + str(recall_score(y_ts,clf_pred_acc)))
print('F1 Score : ' + str(f1_score(y_ts,clf_pred_acc)))

#Logistic Regression (Grid Search) Confusion matrix
confusion_matrix(y_ts,clf_pred_acc)

C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regre

{'C': 0.009, 'penalty': 'l2'} 

Accuracy Score : 0.9095171934699549
Precision Score : 0.9459152798789713
Recall Score : 0.8687044112539076
F1 Score : 0.9056672098497193


C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([[2736,  143],
       [ 378, 2501]], dtype=int64)

In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from sklearn.feature_selection import VarianceThreshold
var = VarianceThreshold()
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
sampler = SMOTE()
rf = RandomForestClassifier()

pipe_rf = Pipeline([('scaler', sc),
                  ('selector', var),
                  ('sampler', sampler),
                  ('model', rf)])

grid_rf = {'selector__threshold': [0, 0.2, 0.4],
         'model__n_estimators': [20, 50, 100]}

clf_rf = GridSearchCV(pipe_rf, grid_rf, cv=3)
clf_rf.fit(X_tr, y_tr)

GridSearchCV(cv=3, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('scaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('selector',
                                        VarianceThreshold(threshold=0.0)),
                                       ('sampler',
                                        SMOTE(k_neighbors=5, n_jobs=None,
                                              random_state=None,
                                              sampling_strategy='auto')),
                                       ('model',
                                        RandomForestClassifier(bootstrap=True,
                                                               ccp_alpha=0.0,
                                                               

In [83]:
from sklearn.metrics import classification_report , accuracy_score , precision_recall_fscore_support
preds_rf=clf_rf.predict(X_ts)
print(clf_rf.best_params_, '\n')
print('accuracy: {:.2f}%'.format(accuracy_score(y_ts, preds_rf)*100))

print(classification_report(y_ts, preds_rf))
confusion_matrix(y_ts,preds_rf)

{'model__n_estimators': 100, 'selector__threshold': 0.4} 

accuracy: 98.87%
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      2879
           1       0.98      0.99      0.99      2879

    accuracy                           0.99      5758
   macro avg       0.99      0.99      0.99      5758
weighted avg       0.99      0.99      0.99      5758



array([[2835,   44],
       [  21, 2858]], dtype=int64)

In [ ]:
from sklearn.metrics import classification_report , accuracy_score , precision_recall_fscore_support
preds_rf=clf_rf.predict(X_ts)
print(clf_rf.best_params_, '\n')
print('accuracy: {:.2f}%'.format(accuracy_score(y_ts, preds_rf)*100))

print(classification_report(y_ts, preds_rf))
confusion_matrix(y_ts,preds_rf)

In [85]:
grid_rf2 = {'selector__threshold': [0.3, 0.4, 0.5],
         'model__n_estimators': [80, 100, 120]}

clf_rf2 = GridSearchCV(pipe_rf, grid_rf2, cv=3)
clf_rf2.fit(X_tr, y_tr)
from sklearn.metrics import classification_report , accuracy_score , precision_recall_fscore_support
preds_rf2=clf_rf2.predict(X_ts)
print(clf_rf2.best_params_, '\n')
print('accuracy: {:.2f}%'.format(accuracy_score(y_ts, preds_rf2)*100))

print(classification_report(y_ts, preds_rf2))
confusion_matrix(y_ts,preds_rf2)

{'model__n_estimators': 120, 'selector__threshold': 0.3} 

accuracy: 98.87%
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      2879
           1       0.98      0.99      0.99      2879

    accuracy                           0.99      5758
   macro avg       0.99      0.99      0.99      5758
weighted avg       0.99      0.99      0.99      5758



array([[2835,   44],
       [  21, 2858]], dtype=int64)