In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [3]:
data_test= pd.read_csv('data_for_testing.csv', delimiter=";")
data_from_users= pd.read_csv('data_from_users.csv', delimiter=";")
users_featured= pd.read_csv('users_featured.csv', delimiter=";")

In [4]:
from sklearn.model_selection import train_test_split

X = data_test.drop(columns=['plan']).values
X_columns = data_test.drop(columns=['plan']).columns
y = data_test['plan'].values

data_test.plan.value_counts()

0    14394
1     1150
Name: plan, dtype: int64

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import VarianceThreshold
var = VarianceThreshold()
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
sampler = SMOTE()
rf = RandomForestClassifier()
from sklearn.tree import DecisionTreeClassifier
#Logistic Regression Classifier Confusion matrix
from sklearn.metrics import confusion_matrix

In [6]:
# transform the dataset
oversample = SMOTE()
X, y = oversample.fit_resample(X, y)
print(X.shape)
print(y.shape)

(28788, 51)
(28788,)


In [7]:
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y, test_size=0.2, stratify=y)
X_ts.shape

(5758, 51)

In [8]:
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y, test_size=0.2, stratify=y)
y_ts.shape

(5758,)

Feature Selection

In [9]:
X.shape

(28788, 51)

In [10]:
from sklearn.svm import LinearSVC
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectFromModel
lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape

(28788, 38)

In [11]:
X_tr, X_ts, y_tr, y_ts = train_test_split(X_new, y, test_size=0.2, stratify=y)
X_ts.shape

(5758, 38)

Training Model

In [24]:
grid_dtc2 = {'criterion': ['gini'],
        'splitter': ['best'],
        'max_depth': [None, 14, 12, 10, 8, 6]}


clf_grid_dtc3 = GridSearchCV(dtc, grid_dtc2, scoring='recall', cv=7, verbose=1)

clf_grid_dtc3.fit(X_tr, y_tr)
from sklearn.metrics import classification_report , accuracy_score , precision_recall_fscore_support
preds_dtc3=clf_grid_dtc3.predict(X_ts)
print(clf_grid_dtc3.best_params_, '\n')
print('accuracy: {:.2f}%'.format(accuracy_score(y_ts, preds_dtc3)*100))

print(classification_report(y_ts, preds_dtc3))
confusion_matrix(y_ts,preds_dtc3)

Fitting 7 folds for each of 6 candidates, totalling 42 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  42 out of  42 | elapsed:   13.1s finished


{'criterion': 'gini', 'max_depth': 6, 'splitter': 'best'} 

accuracy: 97.41%
              precision    recall  f1-score   support

           0       0.99      0.96      0.97      2879
           1       0.96      0.99      0.97      2879

    accuracy                           0.97      5758
   macro avg       0.97      0.97      0.97      5758
weighted avg       0.97      0.97      0.97      5758



array([[2761,  118],
       [  31, 2848]], dtype=int64)

In [19]:
dtc = DecisionTreeClassifier()


grid_dtc = {'criterion': ['gini', 'entropy'],
        'splitter': ['best', 'random'],
        'max_depth': [None, 100, 50, 20, 10, 5]}


clf_grid_dtc = GridSearchCV(dtc, grid_dtc, scoring='accuracy', cv=3, verbose=1)

clf_grid_dtc.fit(X_tr, y_tr)

Fitting 3 folds for each of 24 candidates, totalling 72 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  72 out of  72 | elapsed:   11.1s finished


GridSearchCV(cv=3, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                   

In [20]:
from sklearn.metrics import classification_report , accuracy_score , precision_recall_fscore_support
preds_dtc=clf_grid_dtc.predict(X_ts)
print(clf_grid_dtc.best_params_, '\n')
print('accuracy: {:.2f}%'.format(accuracy_score(y_ts, preds_dtc)*100))

print(classification_report(y_ts, preds_dtc))
confusion_matrix(y_ts,preds_dtc)

{'criterion': 'gini', 'max_depth': 10, 'splitter': 'best'} 

accuracy: 98.09%
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      2879
           1       0.99      0.98      0.98      2879

    accuracy                           0.98      5758
   macro avg       0.98      0.98      0.98      5758
weighted avg       0.98      0.98      0.98      5758



array([[2838,   41],
       [  69, 2810]], dtype=int64)

In [23]:
grid_dtc2 = {'criterion': ['gini'],
        'splitter': ['best'],
        'max_depth': [None, 14, 12, 10, 8, 6]}


clf_grid_dtc2 = GridSearchCV(dtc, grid_dtc2, scoring='accuracy', cv=7, verbose=1)

clf_grid_dtc2.fit(X_tr, y_tr)
from sklearn.metrics import classification_report , accuracy_score , precision_recall_fscore_support
preds_dtc2=clf_grid_dtc2.predict(X_ts)
print(clf_grid_dtc2.best_params_, '\n')
print('accuracy: {:.2f}%'.format(accuracy_score(y_ts, preds_dtc2)*100))

print(classification_report(y_ts, preds_dtc2))
confusion_matrix(y_ts,preds_dtc2)

Fitting 7 folds for each of 6 candidates, totalling 42 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  42 out of  42 | elapsed:   13.2s finished


{'criterion': 'gini', 'max_depth': 12, 'splitter': 'best'} 

accuracy: 98.37%
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      2879
           1       0.98      0.98      0.98      2879

    accuracy                           0.98      5758
   macro avg       0.98      0.98      0.98      5758
weighted avg       0.98      0.98      0.98      5758



array([[2830,   49],
       [  45, 2834]], dtype=int64)